// <auto-generated />
using System;
using Limupa.Comment.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Limupa.Comment.Api.Migrations
{
    [DbContext(typeof(CommentContext))]
    [Migration("20240528183220_limupa_comment_mig_docker_one")]
    partial class limupa_comment_mig_docker_one
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Limupa.Comment.Api.Entities.UserComment", b =>
                {
                    b.Property<int>("UserCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCommentID"));

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCommentCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCommentDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCommentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCommentImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCommentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserCommentRating")
                        .HasColumnType("int");

                    b.Property<bool>("UserCommentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("UserCommentSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserCommentID");

                    b.ToTable("UserComments");
                });
#pragma warning restore 612, 618
        }
    }
}
